[env]
# This is the most important variable.
# It forces vcpkg to find libraries that are compatible with static linking.
VCPKG_CRT_LINKAGE = "static"

# While the above is key, we will also set the default triplet
# as a "belt and suspenders" measure to be absolutely clear.
VCPKG_DEFAULT_TRIPLET = "x64-windows-static"