name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for build workflow to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Build Linux'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Download Linux artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          name: linux-binaries
          path: artifacts/linux-binaries/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}

      - name: Download Windows artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          name: windows-binaries
          path: artifacts/windows-binaries/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/linux-binaries/*.deb
            artifacts/linux-binaries/*.rpm
            artifacts/windows-binaries/*.msi
            artifacts/windows-binaries/*.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
